biuropodrozy/users/urls.py
from django.urls import path

from biuropodrozy.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    user_delete_view,
    del_user,
    user_reservations_view
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("reservations/", view=user_reservations_view, name="reservations"),
    path("delete/", view=user_delete_view, name="delete"),
    path("delconfirm/", view=del_user, name="deleteconfirm"),
    path("<str:username>/", view=user_detail_view, name="detail"),


]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from biuropodrozy.users.views import ContactCreateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('oferty/', include("travels.urls", namespace="travels")),
    path('kontakt/', ContactCreateView.as_view(), name='contact'),
    #path('kontakt/',TemplateView.as_view(template_name="pages/about.html"), name='contact'),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("biuropodrozy.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

biuropodrozy/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models


class User(AbstractUser):
    """Default user for BiuroPodrozy."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


class Contact(models.Model):
    email = models.EmailField(max_length=50)
    description = models.TextField(max_length=500)

biuropodrozy/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Row, Column
from django.forms import ModelForm
from biuropodrozy.users.models import Contact

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class ContactForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = True

        self.helper.layout = Layout(Fieldset(
            _(""),
            Row(
                Column("email", css_class="form-group col-md-8 mb-0")
            ),
            "description",
            ),
            ButtonHolder(Submit("submit", "Wyślij", css_class="button white")),
        )

    class Meta:
        model = Contact
        fields = "__all__"

biuropodrozy/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

biuropodrozy/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, ListView
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib import messages
from travels.models import TripReservation
from biuropodrozy.users.models import Contact
from django.views.generic.edit import CreateView
from biuropodrozy.users.forms import ContactForm
from django.urls import reverse_lazy

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserReservationsView(LoginRequiredMixin, ListView):
    template_name = 'users/user_reservations.html'
    model = TripReservation
    paginate_by = 5
    context_object_name = "reservations"

    def get_queryset(self):
        return TripReservation.objects.filter(user=self.request.user)


user_reservations_view = UserReservationsView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserDeleteView(TemplateView):
    template_name = 'users/user_delete.html'


user_delete_view = UserDeleteView.as_view()


def del_user(request):
    try:
        u = request.user
        u.delete()
        messages.success(request, 'Konto zostało usunięte')

    except User.DoesNotExist:
        messages.error(request, 'Użytkownik nie istnieje')
        return render(request, 'pages/home.html')

    except Exception:
        messages.error(request, 'Wystąpił błąd')
        return render(request, 'pages/home.html')

    return render(request, 'pages/home.html')


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class ContactCreateView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'pages/contact.html'
    success_url = reverse_lazy('contact')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'Dziekujemy za złożenie pytania, postaramy się odpisać jak najszybciej')
        return result

biuropodrozy/templates/users/user_delete.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Delete account" %}{% endblock %}

{% block inner %}
<h1>{% trans "Usuń konto" %}</h1>

<p>{% trans 'Czy na pewno chcesz usunąć konto?' %}</p>

<form method="post" action="{% url 'users:deleteconfirm' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button class="btn btn-danger" type="submit">{% trans 'Usuń konto' %}</button>
</form>


{% endblock %}

biuropodrozy/templates/users/user_detail.html
{% extends "account/base.html" %}
{% load static i18n %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block inner %}
<div class="container">
  <h1>{% trans "Mój Profil" %}</h1>

  <div class="row">
    <div class="col-sm-12">

      <h2>{% trans "Nazwa użytkownika" %}: {{ object.username }}</h2>
      {% if object.emailaddress_set.all %}
        {% for emailaddress in user.emailaddress_set.all %}
        <p>{% trans "Email address" %}: {{ emailaddress.email }}</p>
        {% endfor %}
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <!--<a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>-->
    <a class="btn btn-info" href="{% url 'users:reservations' %}" role="button">Moje rezerwacje</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Dodaj/Usuń E-Mail</a>
    <a class="btn btn-primary" href="{% url 'account_reset_password' %}" role="button">Zmień hasło</a>
    <a class="btn btn-danger" href="{% url 'users:delete' %}" role="button">Usuń konto</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock inner %}

biuropodrozy/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

biuropodrozy/templates/users/user_reservations.html
{% extends "account/base.html" %}
{% load static i18n %}

{% block inner %}
  <table class="table table-bordered table-hover table-responsive">
    <thead class="thead-dark">
        <tr>
            <th>
                Nazwa wycieczki
            </th>
            <th>
                Ilość osób
            </th>
            <th>
                Dodatkowe opcje:
            </th>
            <th>
                Data rozpoczęcia
            </th>
            <th>
                Data zakończenia:
            </th>
            <th>
                Cena:
            </th>
        </tr>
    </thead>
    <tbody>
          {% for reservation in reservations %}
        <tr>
            <td>
              <a href="{{ reservation.trip.get_absolute_url}}">{{reservation.trip}}</a>
            </td>
            <td>
                {{reservation.persons}}
            </td>

            <td>
              <ul class="list-group">
                <li>
                Prywatny przewodnik: {% if reservation.guide == True %}
                  TAK
                  {% else %} NIE
                  {% endif %}
                </li>
                <li>
                Pokój premium: {% if reservation.room == True %}
                  TAK
                  {% else %} NIE
                  {% endif %}
                </li>
                <li>
                All Inclusive: {% if reservation.all_inclusive == True %}
                  TAK
                  {% else %} NIE
                  {% endif %}
                </li>
              </ul>
            </td>
            <td>
                {{reservation.date.start_date}}
            </td>

            <td>
                {{reservation.date.end_date}}
            </td>
            <td>
                {{reservation.price}}zł
            </td>
        </tr>
          {% endfor %}
    </tbody>
</table>

{% endblock inner %}