config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from biuropodrozy.users.views import ContactCreateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('oferty/', include("travels.urls", namespace="travels")),
    path('kontakt/', ContactCreateView.as_view(), name='contact'),
    #path('kontakt/',TemplateView.as_view(template_name="pages/about.html"), name='contact'),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("biuropodrozy.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

travels/urls.py
from django.urls import path
from . import views

from travels.views import (SelectedForYouListView, TripDetailView, QuestionnaireView, PopularListView, OthersChooseListView)

app_name = "travels"
urlpatterns = [
    path("", PopularListView.as_view(), name="popular"),
    path("selectedforyou", SelectedForYouListView.as_view(), name="selected_for_you"),
    path("otherschoose", OthersChooseListView.as_view(), name="otherschoose"),
    path("polling", QuestionnaireView.as_view(), name="polling"),
    path("<str:slug>/", TripDetailView.as_view(), name="details"),
]

travels/forms.py
from django.forms import ModelForm, HiddenInput
from travels.models import TripReservation, Polling
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Row, Column
from django.utils.translation import gettext as _
from django import forms


class TripReservationForm(ModelForm):
    """
    Klasa reprezentująca formularz rezerwacji
    """

    select_dates = []

    def __init__(self, *args, **kwargs):
        """
        Metoda odpowiadająca za inicjalizację pól
        """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = True
        self.fields['user'].widget = HiddenInput()
        self.fields['trip'].widget = HiddenInput()
        self.fields['date'].widget = forms.Select(choices=self.select_dates)

        self.helper.layout = Layout(Fieldset(
            _("Złóż rezerwację"),
            "date",
            "persons",
            "phone",
            "guide",
            "room",
            "all_inclusive",
            "trip",
            "user",
            ),
            ButtonHolder(Submit("submit", "Rezerwuj", css_class="button white")),
        )

    class Meta:
        """
            Przypisanie modelu rezerwacji i potrzebnych pól
        """
        model = TripReservation
        fields = '__all__'


class PollingForm(ModelForm):
    """
        Klasa reprezentująca formularz ankiety
    """
    def __init__(self, *args, **kwargs):
        """
            Metoda odpowiadająca za inicjalizację pól
        """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = True
        self.fields['user'].widget = HiddenInput()

        self.helper.layout = Layout(Fieldset(
            _("Ankieta"),
            Row(
                Column("preferred_place", css_class="form-group col-md-8 mb-0")
            ),
            Row(
                Column("preferred_transport", css_class="form-group col-md-8 mb-0")
            ),
            Row(
                Column("preferred_type", css_class="form-group col-md-8 mb-0")
            ),
            Row(
                Column("preferred_landscape", css_class="form-group col-md-8 mb-0")
            ),
            "user",
            ),
            ButtonHolder(Submit("submit", "Wyślij", css_class="btn btn-primary btn-lg")),
        )

    class Meta:
        """
            Przypisanie modelu rezerwacji i potrzebnych pól
        """
        model = Polling
        fields = '__all__'

travels/views.py
from django.contrib import messages
from .models import Trip, TripPicture, TripDates, Polling, TripReservation
from django.views.generic.edit import CreateView
from .forms import TripReservationForm, PollingForm
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
import travels.content_based_recommendation as cbr
from travels.helper import Helper
import travels.memory_based_collaborative_filtering as mbcf


class SelectedForYouListView(ListView):
    model = Trip
    template_name = 'travels/trip_list.html'
    paginate_by = 12
    context_object_name = "trips"
    ankieta = None

    def get_context_data(self, **kwargs):
        context = super(SelectedForYouListView, self).get_context_data(**kwargs)
        context['pictures'] = TripPicture.objects.all().filter(default=True, trip__in=self.get_queryset()[:50])
        if self.request.user.is_authenticated:
            context['polling'] = self.ankieta
        return context

    def get_queryset(self):
        if self.request.user.is_authenticated:
            user_reservations = TripReservation.manager_objects.user_reservations(self.request.user)
            result_set = set()
            for reservation in user_reservations:
                try:
                    result_set.update(cbr.get_result(reservation.trip.title))
                except IndexError:
                    print("Brak wycieczki w V2csv.csv")
                except Exception:
                    print("Error")
            self.ankieta = Polling.objects.filter(user=self.request.user).last()
            if self.ankieta is not None:
                polling_query = Helper.get_polling_query(self.ankieta)
                for trip in polling_query:
                    if not result_set.__contains__(trip.title):
                        result_set.add(trip.title)
            query = Trip.objects.filter(title__in=result_set).order_by('-rating')
            return query

        return Trip.objects.none()


class PopularListView(ListView):
    model = Trip
    paginate_by = 12
    context_object_name = "trips"
    template_name = "travels/trip_list.html"

    def get_context_data(self, **kwargs):
        context = super(PopularListView, self).get_context_data(**kwargs)
        context['pictures'] = TripPicture.objects.all().filter(default=True, trip__in=self.get_queryset()[:50])
        if self.request.user.is_authenticated:
            context['polling'] = Polling.objects.filter(user=self.request.user).last()
        return context

    def get_queryset(self):
        return Helper.popular


class OthersChooseListView(ListView):
    model = Trip
    paginate_by = 12
    context_object_name = "trips"

    def get_context_data(self, **kwargs):
        context = super(OthersChooseListView, self).get_context_data(**kwargs)
        context['pictures'] = TripPicture.objects.all().filter(default=True, trip__in=self.get_queryset()[:50])
        if self.request.user.is_authenticated:
            context['polling'] = Polling.objects.filter(user=self.request.user).last()
        return context

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return mbcf.get_result(self.request.user)
        return Trip.objects.none()


class TripDetailView(FormMixin, DetailView):
    model = Trip
    context_object_name = "trip"
    form_class = TripReservationForm

    def get_context_data(self, **kwargs):
        context = super(TripDetailView, self).get_context_data(**kwargs)
        context['pictures'] = TripPicture.objects.all().filter(trip=context['trip'])
        context['dates'] = TripDates.objects.filter(trip=context['trip'])
        TripReservationForm.select_dates=self.get_data(context['dates'])
        context['form'] = self.form_class(initial={'user': self.request.user, 'trip': self.object})

        return context

    def get_success_url(self):
        return reverse("travels:details", kwargs={"slug": self.object.slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            messages.success(request, f'Rezerwacja została złożona')
            return self.form_valid(form)
        else:
            print(form.cleaned_data)
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save(False)
        print(form.cleaned_data)
        form.save()
        return super(TripDetailView, self).form_valid(form)

    def get_data(self, data):
        choices = list(data)
        select_dates = []
        for value in choices:
            select_dates.append((value.pk, value.start_date))
        return select_dates


class QuestionnaireView(LoginRequiredMixin, CreateView):
    model = Polling
    form_class = PollingForm
    success_url = reverse_lazy('travels:selected_for_you')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'Dziękujemy za wypełnienie ankiety')
        return result

travels/templates/travels/polling_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/polling.css'%}">
{% endblock css %}

{% block content %}
<div class="container">
<div class="pollingWindow">
  {% crispy form%}
</div>
</div>
{% endblock content %}

travels/templates/travels/trip_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/trip_details.css'%}">
{% endblock css %}

{% block content %}

  <div class="d-flex justify-content-evenly flex-wrap p-4 m-4 rounded" id="tcontainer">
    <div class="flex-fill left_side">
      <h1 class="title">{{ trip.title }}</h1>
        {% for picture in pictures %}
        {% if picture.trip == trip %}
        <img class="rounded" src="{{ picture.picture_url }}">
        {% endif %}
        {% endfor %}
      <hr>
      <h2>{{ trip.city }}</h2>
      {% if trip.rating != None %}
        <h2>Ocena: {{ trip.rating }}/6</h2>
      {% endif %}
      {% if trip.hotelstars != None %}
        <h2>Gwiazdki hotelowe: {{trip.hotelstars}}</h2>
      {% endif %}
      <h2>Czas trwania: {{ trip.duration }} dni</h2>
      <h2 style="text-align:right;"><strong>Cena od <span id="tripPrice">{{ trip.price }} </span> zł/os</strong></h2>
      <hr>
      <div class="descriptions">
        <h6>{{ trip.head_description|linebreaks }}</h6>

        {% if trip.location_description != "" %}
        <h5>POŁOŻENIE</h5>
        <h6>{{ trip.location_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.beach_description != "" %}
        <h5>PLAŻA</h5>
        <h6>{{ trip.beach_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.hotel_description != "" %}
        <h5>HOTEL</h5>
        <h6>{{ trip.hotel_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.room_description != "" %}
        <h5>POKÓJ</h5>
        <h6>{{ trip.room_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.sport_and_entertainment_description != "" %}
        <h5>SPORT I ROZRYWKA</h5>
        <h6>{{ trip.sport_and_entertainment_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.all_inclusive_description != "" %}
        <h5>ALL INCLUSIVE (ZA DOPŁATĄ)</h5>
        <h6>{{ trip.all_inclusive_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.for_free_description != "" %}
        <h5>GRATIS</h5>
        <h6>{{ trip.for_free_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.trip_plan_description != "" %}
        <h5>PLAN WYCIECZKI</h5>
        <h6>{{ trip.trip_plan_description|linebreaks }}</h6>
        {% endif %}

        {% if trip.benefits_description != "" %}
        <h5>ŚWIADCZENIA</h5>
        <h6>{{ trip.benefits_description|linebreaks }}</h6>
        {% endif %}
        </div>
    </div>
    <div class="flex-fill pl-5">
      {% if trip.countryEN != "" %}
      <div class="weather">
        <h2>Pogoda:</h2>
        <h2>Dziś: {{trip.weather_api.temp_today}} {{trip.weather_api.desc_today}}</h2>
        <h2>{{trip.weather_api.next1day_name}}: {{trip.weather_api.temp_next1day}}</h2>
        <h2>{{trip.weather_api.next2day_name}}: {{trip.weather_api.temp_next2day}}</h2>
        <h2>{{trip.weather_api.next3day_name}}: {{trip.weather_api.temp_next3day}}</h2>
      </div>
      {% endif %}
      <hr>
      {% if trip.currency != 'PLN' or trip.currency != '' %}
      {% if trip.exchange_rates_api.rate_in_pln != '' %}
      <div class="exchanges">
        <h2>Kurs: 1{{trip.currency}} = {{ trip.exchange_rates_api.rate_in_pln }}zł</h2>
      </div>
      {% endif %}
      {% endif %}
      <hr>
      {% if trip.countryEN != "" %}
      <div class="covid">
      <h2>Aktualna liczba zachorowań na covid: {{trip.covid_api.today_covid}}</h2>
      </div>
      {% endif %}
      <hr>
      <div id="reservation">
        {% if user.is_authenticated %}
        {% include 'travels/partials/reservation_form.html' %}
        {% else %}
        <h2>Aby złożyć rezerwację musisz się zalogować</h2>
        {% endif %}
      </div>

    </div>
  </div>

{% endblock content %}

{% block inline_javascript %}
  <script type="text/javascript" src="{% static 'js/reservation.js'%}"></script>
{% endblock inline_javascript %}

travels/templates/travels/trip_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/trips.css'%}">
{% endblock css %}

{% block content %}
{% if user.is_authenticated and polling is None %}
<div class="row">
  <div class="col-lg-12">
    <a class="btn btn-primary" href="{% url 'travels:polling' %}">Prosimy o wypełnienie krótkiej
      ankiety w celu znalezienia najlepszych ofert dla Ciebie</a>
  </div>
</div>
{% endif %}


<div class="contOferty">
    <div id="oferty">
      <div class="row">
        <div class="col-lg-4">
          <a class="btn btn-dark" id="b1" href="{% url 'travels:selected_for_you' %}">Wybrane dla Ciebie</a>
        </div>
        <div class="col-lg-4">
          <a class="btn btn-dark" id="b2" href="{% url 'travels:popular' %}">Popularne</a>
        </div>
        <div class="col-lg-4">
          <a class="btn btn-dark" id="b3" href="{% url 'travels:otherschoose' %}">Inni użytkownicy wybrali</a>
        </div>
      </div>
      {% for trip in trips %}
        <a href="{% url 'travels:details' slug=trip.slug %}">
          <div class="boxWycieczki">
            <div class="imgBx">
              <img src="
                {% for picture in pictures %}
                  {% if picture.trip == trip %}
                  {{picture.picture_url}}
                  {% endif %}
                {% endfor %}
               " alt="obrazek wycieczki" onerror="this.src='https://i.content4travel.com/cms/img/u/kraj/1/chorwacja_0.jpg?version=13'">
            </div>

            <span class="szczegoly">Sprawdź szczegóły oferty</span>

            <div class="contentbox">
                <h2>{{trip.title}}<br>
                    <span>
                        {{trip.country}} {{trip.city}}
                        <br>
                        {% if trip.rating != None %}
                        Ocena: {{trip.rating}}/6
                        <br>
                        {% endif %}
                        Czas trwania: {{trip.duration}} dni
                        <br>
                        Cena od {{trip.price}} zł/os.
                    </span>
                </h2>
            </div>
          </div>
        </a>
      {% endfor %}
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pierwsza</a>
            <a href="?page={{ page_obj.previous_page_number }}">poprzednia</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">następna</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">ostatnia &raquo;</a>
          {% endif %}
        </span>
      </div>
    </div>
</div>
{% endblock content %}

{% block inline_javascript %}
  <script type="text/javascript" src="{% static 'js/trips.js'%}"></script>
{% endblock inline_javascript %}